from main_combos import main_intracellular_extracellular
from main_combos import main_intracellular_extra_restricted
from main_combos import main_intra_extra_pard_17e_rest

main_intracellular_extracellular.main()
main_intracellular_extra_restricted.main()
main_intra_extra_pard_17e_rest.main()